project/gamenect/web/router.ex
defmodule Gamenect.Router do
  use Gamenect.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do  
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :needs_admin do
    plug Guardian.Plug.EnsureAuthenticated, handler: Gamenect.UserController
    plug Gamenect.AuthPlug, ["admin", "moderator"]
  end

  scope "/admin", Gamenect do
    pipe_through [:browser, :browser_auth, :needs_admin]
    resources "/games", GameController
  end

  scope "/", Gamenect do
    pipe_through [:browser, :browser_auth]

    get "/", LobbyController, :index
    get "/lobby/join/:id", LobbyController, :join
    resources "/users", UserController
    resources "/lobbies", LobbyController
    resources "/user_lobby", UserLobbyController
    get "/login", UserController, :login
    post "/login", UserController, :login
    get "/logout", UserController, :logout
    get "/confirm/:token", ConfirmationController, :confirm
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", Gamenect do
    pipe_through :api
    get "/game", GameController, :search
  end
end

project/gamenect/web/views/layout_view.ex
defmodule Gamenect.LayoutView do
  use Gamenect.Web, :view
end

project/gamenect/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Gamenect!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <%= render "logged_in.html", assigns %>
        </nav>
        <a href="<%= lobby_path(@conn, :index) %>"><h2 class="app-title">(Gamenect)</h2></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app").AppSearchGame.run()</script>
  </body>
</html>

project/gamenect/web/templates/layout/logged_in.html.eex
<%= if logged_in?(@conn) do %>
  <div class="row">
    <div class="col-md-4 col-xs-4">You are: <%= current_user(@conn).name %></div>
    <div class="col-lg-8 col-xs-4 main-nav">
        <a class="bg-success" href="<%= lobby_path(@conn, :new) %>">Create Lobby<a>
        <a class="bg-primary" href="">Matchmaker<a>
        <a class="bg-danger" href="">Random<a>
        <a class="bg-warning" href="<%= lobby_path(@conn, :index) %>">Lobbies<a>
        <%= if is_allowed?(@conn, ["admin", "moderator"]) do %>
        <a class="bg-warning" href="<%= game_path(@conn, :index) %>">Games<a>
        <a class="bg-warning" href="<%= user_path(@conn, :index) %>">Players<a>
        <% end %>
    </div>
    <div class="col-lg-1 col-xs-1"><%= link "Sign out", to: user_path(@conn, :logout), class: "btn btn-danger" %></div>
  </div>
<% else %>
  <%= link "Create new account", to: user_path(@conn, :new), 
      class: "btn btn-danger" %>
  <%= link "Sign in", to: user_path(@conn, :login), 
      class: "btn btn-danger" %>
<% end %>